# Generated by Django 3.2 on 2021-04-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(blank=True, max_length=126, null=True)),
                ('debtToEquity', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('dividendYield', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('freeCashFlowPerShare', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('marketCap', models.IntegerField(blank=True, null=True)),
                ('priceToBook', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('priceToEarnings', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('industry', models.CharField(blank=True, max_length=126, null=True)),
                ('sector', models.CharField(blank=True, max_length=126, null=True)),
                ('country', models.CharField(blank=True, max_length=126, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('epsNext5Yr', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('epsPrev5Yr', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('epsThisYr', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=3, max_digits=1000, null=True)),
            ],
        ),
    ]
