# Generated by Django 3.2 on 2021-04-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210411_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentalstats',
            name='marketCap',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
    ]
