# Generated by Django 3.2 on 2021-04-19 18:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_fundamentalstats_marketcap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoRates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cryptocurrency', models.CharField(blank=True, max_length=300, null=True)),
                ('exchangeRate', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('historicalHLOC', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('imageURL', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFTStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageURL', models.CharField(blank=True, max_length=300, null=True)),
                ('imageThumbnail', models.CharField(blank=True, max_length=300, null=True)),
                ('animationURL', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('topBid', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
            ],
        ),
    ]
