# Generated by Django 3.2 on 2021-04-20 22:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cryptorates_newsarticles_nftstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoHistorical',
            fields=[
                ('cryptocurrency', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('historicalHLOC', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='cryptorates',
            name='historicalHLOC',
        ),
    ]
