# Generated by Django 3.2 on 2021-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210420_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='imageURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
