# Generated by Django 3.2 on 2021-04-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210420_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftstats',
            old_name='topBid',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='nftstats',
            name='animationURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nftstats',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nftstats',
            name='imageThumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nftstats',
            name='imageURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nftstats',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
