# Generated by Django 3.2 on 2021-04-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210421_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptoHistorical',
            new_name='CryptoDaily',
        ),
        migrations.RenameField(
            model_name='cryptodaily',
            old_name='historicalHLOC',
            new_name='dailyHLOC',
        ),
    ]
