# Generated by Django 3.2 on 2021-04-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210421_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=500)),
                ('coinName', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
