# Generated by Django 3.2 on 2021-04-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cryptocoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoins',
            name='description',
            field=models.TextField(),
        ),
    ]
